# Use an existing base image
FROM eclipse-temurin:25

# Set the working directory in the container
WORKDIR /hytale

EXPOSE 5520/udp

# Copy necessary files into the container
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY webserver /webserver

# Create Dedicated User
RUN useradd -m hytale
USER hytale

# Install dependencies
RUN apt-get update && apt-get install -y \
    wget \
    unzip && \
    apt-get clean

# Run command on container start
ENTRYPOINT ["/entrypoint.sh"]

# Set the default command to execute when the container starts
CMD ["sh", "-c", "/start_server.sh < /webserver/stdin.fifo"]
