# Use an existing base image
FROM eclipse-temurin:25

# Set the working directory in the container
WORKDIR /hytale

EXPOSE 5520/udp

# Copy necessary files into the container
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Install dependencies
RUN apt-get update && apt-get install -y \
    wget \
    unzip && \
    apt-get clean

# Run command on first container start
ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
